# Generated by Django 3.1.7 on 2021-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('New', 'New Product'), ('Hot', 'Hot Products'), ('sale', 'sale product')], default='new', max_length=60),
        ),
    ]
